apiVersion: v1
kind: ReplicationController
metadata:
  name: etech-app-rc 
  namespace: clovis
spec:
  replicas: 3
  selector:
    app: etech-app-rc 
  template:
    metadata:
      name: etech-app-rc 
      labels:
        app: etech-app-rc 
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: etechrc-service
  namespace: clovis 
spec:
  type: NodePort
  selector:
    app: etech-app-rc 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
---

